name: Node.js with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install Dependencies
      run: npm install

    - name: Run Gulp Tasks
      run: gulp build  # Assumes you have a 'build' task defined in your Gulp setup

    - name: Additional Deployment Steps
      run: |
        # Additional commands here if needed, like tests or deployments
        npm run test  # Example command
